import express from "express";
import { addProfile } from "../controllers/userControllers/addProfile";
import { updateProfile } from "../controllers/userControllers/updateProfile";
import { getAllProfile } from "../controllers/userControllers/getAllProfile";
import { getUserProfile } from "../controllers/userControllers/getUserProfile";
import { getCurrentProfile } from "../controllers/userControllers/getCurrentProfile";
import { userExist } from "../middlewares/profileMiddleware/userExist";
import { postValuesValid } from "../middlewares/profileMiddleware/postValuesValid";
import { nameExist } from "../middlewares/profileMiddleware/nameExist";
export const profileRouter = express.Router();
profileRouter.post("/", userExist, postValuesValid, nameExist, addProfile);
profileRouter.put("/", updateProfile);
profileRouter.get("/explore", getAllProfile);
profileRouter.get("/view/:username", getUserProfile);
profileRouter.get("/", getCurrentProfile);
